import { describe, expect, test } from "bun:test";
import {
	buildEmbeddingSpace,
	EMBEDDING_DIM,
	embeddingCosOf,
	generateSimilarities,
	TERM_DF_CAP,
	TOP_K_PER_SEED,
} from "../candidate-generation";
import { buildIdf } from "../scorer";
import type { WorkAggregate, WorkKey } from "../types";
import { workKey } from "../types";

function makeWork(
	id: number,
	overrides: Partial<WorkAggregate> = {},
): WorkAggregate {
	return {
		kind: "book",
		id,
		authorIds: new Set(),
		genreIds: new Set(),
		tagIds: new Set(),
		publisherIds: new Set(),
		languageCode: null,
		memberBookIds: [id],
		embeddingText: "",
		engagedUserIds: new Set(),
		likeCount: 0,
		completionCount: 0,
		rating: null,
		ratingCount: null,
		createdAtMs: 0,
		...overrides,
	};
}

function unitVector(direction: number): number[] {
	const v = new Array(EMBEDDING_DIM).fill(0);
	v[direction % EMBEDDING_DIM] = 1;
	return v;
}

describe("generateSimilarities (inverted index)", () => {
	test("works sharing a rare tag become candidates of each other", () => {
		const works = [
			makeWork(1, { tagIds: new Set([100]) }),
			makeWork(2, { tagIds: new Set([100]) }),
			makeWork(3, { tagIds: new Set([200]) }),
		];
		const pairs = generateSimilarities(
			works,
			{ idf: buildIdf(works), embeddingCos: null },
			null,
		);
		const seeds = new Set(pairs.map((p) => `${p.seed}->${p.cand}`));
		expect(seeds.has("book:1->book:2")).toBe(true);
		expect(seeds.has("book:2->book:1")).toBe(true);
		expect(seeds.has("book:1->book:3")).toBe(false);
	});

	test("terms above the DF cap generate no pairs on their own", () => {
		const works = Array.from({ length: TERM_DF_CAP + 10 }, (_, i) =>
			makeWork(i + 1, { genreIds: new Set([1]) }),
		);
		const pairs = generateSimilarities(
			works,
			{ idf: buildIdf(works), embeddingCos: null },
			null,
		);
		expect(pairs.length).toBe(0);
	});

	test("taxonomy terms shared by too much of a small catalog generate no pairs", () => {
		const works = Array.from({ length: 60 }, (_, i) =>
			makeWork(i + 1, { genreIds: i < 20 ? new Set([1]) : new Set() }),
		);
		const pairs = generateSimilarities(
			works,
			{ idf: buildIdf(works), embeddingCos: null },
			null,
		);
		expect(pairs.length).toBe(0);
	});

	test("a merely broad genre is insufficient evidence by itself", () => {
		const works = Array.from({ length: 20 }, (_, i) =>
			makeWork(i + 1, { genreIds: i < 8 ? new Set([1]) : new Set() }),
		);
		const pairs = generateSimilarities(
			works,
			{ idf: buildIdf(works), embeddingCos: null },
			null,
		);
		expect(pairs).toEqual([]);
	});

	test("capped terms still score pairs generated by rare terms", () => {
		const works = Array.from({ length: TERM_DF_CAP + 10 }, (_, i) =>
			makeWork(i + 1, {
				genreIds: new Set([1]),
				tagIds: i < 2 ? new Set([99]) : new Set(),
			}),
		);
		const pairs = generateSimilarities(
			works,
			{ idf: buildIdf(works), embeddingCos: null },
			null,
		);
		const pair = pairs.find((p) => p.seed === "book:1" && p.cand === "book:2");
		expect(pair).toBeDefined();
		// the capped genre contributed to the score (component > 0), tiny idf but > 0
		expect(pair?.components.genre).toBeGreaterThanOrEqual(0);
		expect(pair?.components.tag).toBeGreaterThan(0);
	});

	test("no self-pairs", () => {
		const works = [
			makeWork(1, { authorIds: new Set([1]) }),
			makeWork(2, { authorIds: new Set([1]) }),
		];
		const pairs = generateSimilarities(
			works,
			{ idf: buildIdf(works), embeddingCos: null },
			null,
		);
		expect(pairs.every((p) => p.seed !== p.cand)).toBe(true);
	});

	test("top-K per seed cap holds", () => {
		// 50 works all sharing one author (under DF cap) → each seed sees 49 candidates
		const works = Array.from({ length: 50 }, (_, i) =>
			makeWork(i + 1, { authorIds: new Set([7]) }),
		);
		const pairs = generateSimilarities(
			works,
			{ idf: buildIdf(works), embeddingCos: null },
			null,
		);
		const bySeed = new Map<string, number>();
		for (const p of pairs) bySeed.set(p.seed, (bySeed.get(p.seed) ?? 0) + 1);
		for (const count of bySeed.values())
			expect(count).toBeLessThanOrEqual(TOP_K_PER_SEED);
	});
});

describe("generateSimilarities (semantic candidates)", () => {
	test("embedding neighbors with no shared terms still become candidates", () => {
		// two works share an embedding direction but no structured terms
		const works = [makeWork(1), makeWork(2), makeWork(3)];
		const space = buildEmbeddingSpace([
			{ key: workKey("book", 1), vector: unitVector(0) },
			{ key: workKey("book", 2), vector: unitVector(0) },
			{ key: workKey("book", 3), vector: unitVector(5) },
		]);
		const ctx = { idf: buildIdf(works), embeddingCos: embeddingCosOf(space) };
		const pairs = generateSimilarities(works, ctx, space);
		const pair = pairs.find((p) => p.seed === "book:1" && p.cand === "book:2");
		expect(pair).toBeDefined();
		expect(pair?.reason).toBe("similar_content");
		// orthogonal vector never pairs (cos 0 → embSim 0 → score 0)
		expect(
			pairs.find((p) => p.seed === "book:1" && p.cand === "book:3"),
		).toBeUndefined();
	});

	test("without embedding space only structured pairs exist", () => {
		const works = [makeWork(1), makeWork(2)];
		const pairs = generateSimilarities(
			works,
			{ idf: buildIdf(works), embeddingCos: null },
			null,
		);
		expect(pairs.length).toBe(0);
	});

	test("weak embedding-only neighbors are rejected", () => {
		const works = [makeWork(1), makeWork(2)];
		const first = unitVector(0);
		const second = new Array(EMBEDDING_DIM).fill(0);
		second[0] = 0.83; // embeddingSimilarity = (0.83-0.78)/0.14 ≈ 0.36 < 0.55 gate
		second[1] = Math.sqrt(1 - 0.83 ** 2);
		const space = buildEmbeddingSpace([
			{ key: workKey("book", 1), vector: first },
			{ key: workKey("book", 2), vector: second },
		]);
		const pairs = generateSimilarities(
			works,
			{ idf: buildIdf(works), embeddingCos: embeddingCosOf(space) },
			space,
		);
		expect(pairs).toEqual([]);
	});

	test("dead-zone neighbors (~0.885 cosine) now pair on embedding alone", () => {
		// regression: (cos-0.75)/0.25 mapped 0.885 → 0.54, just under the gate, so
		// content-only works with no shared author/genre stayed isolated forever
		const works = [makeWork(1), makeWork(2)];
		const first = unitVector(0);
		const second = new Array(EMBEDDING_DIM).fill(0);
		second[0] = 0.885; // embeddingSimilarity = (0.885-0.78)/0.14 = 0.75 ≥ 0.55 gate
		second[1] = Math.sqrt(1 - 0.885 ** 2);
		const space = buildEmbeddingSpace([
			{ key: workKey("book", 1), vector: first },
			{ key: workKey("book", 2), vector: second },
		]);
		const pairs = generateSimilarities(
			works,
			{ idf: buildIdf(works), embeddingCos: embeddingCosOf(space) },
			space,
		);
		const pair = pairs.find((p) => p.seed === "book:1" && p.cand === "book:2");
		expect(pair).toBeDefined();
		expect(pair?.reason).toBe("similar_content");
	});

	test("moderate embeddings cannot override incompatible known genres", () => {
		const works = [
			makeWork(1, { genreIds: new Set([1]) }),
			makeWork(2, { genreIds: new Set([2]) }),
		];
		const first = unitVector(0);
		const second = new Array(EMBEDDING_DIM).fill(0);
		// embeddingSimilarity = (0.864-0.78)/0.14 = 0.6: clears the 0.55 gate but
		// not the 0.65 contradicting-genre gate, so the genre conflict blocks it
		second[0] = 0.864;
		second[1] = Math.sqrt(1 - 0.864 ** 2);
		const space = buildEmbeddingSpace([
			{ key: workKey("book", 1), vector: first },
			{ key: workKey("book", 2), vector: second },
		]);
		const pairs = generateSimilarities(
			works,
			{ idf: buildIdf(works), embeddingCos: embeddingCosOf(space) },
			space,
		);
		expect(pairs).toEqual([]);
	});
});

describe("embeddingCosOf", () => {
	test("returns null for unknown keys and exact cosine for known ones", () => {
		const space = buildEmbeddingSpace([
			{ key: workKey("book", 1), vector: unitVector(0) },
			{ key: workKey("book", 2), vector: unitVector(0) },
		]);
		const cos = embeddingCosOf(space);
		expect(cos(workKey("book", 1), workKey("book", 2))).toBeCloseTo(1);
		expect(cos(workKey("book", 1), workKey("book", 999) as WorkKey)).toBeNull();
	});
});
