CREATE TYPE "public"."library_overwrite_subject" AS ENUM('everyone', 'role', 'user');--> statement-breakpoint
CREATE TABLE "library_permission_overwrite" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "library_permission_overwrite_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"library_id" bigint NOT NULL,
	"organization_id" text NOT NULL,
	"subject_type" "library_overwrite_subject" NOT NULL,
	"subject_id" text,
	"allow" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"deny" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "member_role" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "member_role_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"role_id" text NOT NULL,
	"organization_id" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "role" (
	"id" text PRIMARY KEY NOT NULL,
	"organization_id" text NOT NULL,
	"name" text NOT NULL,
	"color" text,
	"position" integer DEFAULT 0 NOT NULL,
	"is_default" boolean DEFAULT false NOT NULL,
	"permissions" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "library_permission_overwrite" ADD CONSTRAINT "library_permission_overwrite_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "library_permission_overwrite" ADD CONSTRAINT "library_permission_overwrite_library_id_fkey" FOREIGN KEY ("library_id") REFERENCES "public"."library"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "member_role" ADD CONSTRAINT "member_role_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "member_role" ADD CONSTRAINT "member_role_role_id_role_id_fk" FOREIGN KEY ("role_id") REFERENCES "public"."role"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "member_role" ADD CONSTRAINT "member_role_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "role" ADD CONSTRAINT "role_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "lpo_unique_idx" ON "library_permission_overwrite" USING btree ("library_id","subject_type","subject_id");--> statement-breakpoint
CREATE INDEX "lpo_library_idx" ON "library_permission_overwrite" USING btree ("library_id");--> statement-breakpoint
CREATE UNIQUE INDEX "member_role_unique_idx" ON "member_role" USING btree ("user_id","role_id");--> statement-breakpoint
CREATE INDEX "member_role_user_org_idx" ON "member_role" USING btree ("user_id","organization_id");--> statement-breakpoint
CREATE UNIQUE INDEX "role_org_name_idx" ON "role" USING btree ("organization_id","name");--> statement-breakpoint
CREATE INDEX "role_org_idx" ON "role" USING btree ("organization_id");