// Post-build: writes dist/client/sw-precache.js so the SW precaches the app
// shell at install. The embedded hash changes per build, which is what makes
// the browser reinstall the worker. Fonts excluded (several MB of CJK subsets).

import path from "node:path";

const clientDir = path.join(import.meta.dir, "../dist/client");

const assets: string[] = [];
for await (const file of new Bun.Glob("assets/**/*.{js,css}").scan({
	cwd: clientDir,
	onlyFiles: true,
})) {
	assets.push(`/${file.split(path.sep).join(path.posix.sep)}`);
}
assets.sort();

if (assets.length === 0) {
	console.error("build-sw-precache: no assets found — did vite build run?");
	process.exit(1);
}

const buildHash = Bun.hash(assets.join("\n")).toString(16);
const body = `// Generated by scripts/build-sw-precache.ts — build ${buildHash}\nself.__PRECACHE_MANIFEST = ${JSON.stringify(assets, null, "\t")};\n`;

await Bun.write(path.join(clientDir, "sw-precache.js"), body);
console.log(
	`build-sw-precache: ${assets.length} assets manifested (build ${buildHash})`,
);
