import { afterAll, beforeAll, describe, expect, mock, test } from "bun:test";
import { readFile } from "node:fs/promises";
import { drizzle } from "drizzle-orm/node-postgres";
import { Pool } from "pg";

const enabled = process.env.AUDIOBOOK_SERIES_INTEGRATION === "1";
describe.skipIf(!enabled)("audiobook series transactions and migration", () => {
	const connection = {
		host: process.env.DB_HOST,
		port: Number(process.env.DB_PORT),
		user: process.env.DB_USER,
		password: process.env.DB_PASSWORD,
		database: process.env.DB_NAME,
	};
	const schema = `series_test_${crypto.randomUUID().replaceAll("-", "")}`;
	let admin: Pool;
	let pool: Pool;
	let repo: import("../metadata.repository").AudiobookMetadataRepository;
	const identity = {
		provider: "audible" as const,
		providerId: "B07H7GGCC7",
		region: "jp",
	};
	beforeAll(async () => {
		admin = new Pool(connection);
		await admin.query(`CREATE SCHEMA ${schema}`);
		pool = new Pool({
			...connection,
			options: `-c search_path=${schema},public`,
		});
		// A pre-migration schema isolates this test from the development catalog.
		await pool.query(`CREATE TABLE organization(id text PRIMARY KEY);
   CREATE TABLE series(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,uuid uuid DEFAULT gen_random_uuid(),name text NOT NULL,aliases text[] DEFAULT '{}',description text,created_at timestamp DEFAULT now(),server_id text NOT NULL REFERENCES organization,UNIQUE(server_id,name));
   CREATE TABLE library(id int PRIMARY KEY,server_id text NOT NULL REFERENCES organization);
   CREATE TABLE book(id bigint PRIMARY KEY,uuid uuid DEFAULT gen_random_uuid(),filename text NOT NULL,library_id int REFERENCES library,group_locked boolean DEFAULT false,duplicate_of_book_id bigint);
   CREATE TABLE audiobook_metadata(book_id bigint PRIMARY KEY REFERENCES book,title text,asin text,duration double precision,locked_fields text[] NOT NULL DEFAULT '{}',field_sources jsonb NOT NULL DEFAULT '{}');
   CREATE TABLE audiobook_series(book_id bigint REFERENCES audiobook_metadata,series_id bigint REFERENCES series,position double precision,PRIMARY KEY(book_id,series_id));`);
		const migration = await readFile(
			new URL(
				"../../../../../../db/src/migrations/0111_bizarre_salo.sql",
				import.meta.url,
			),
			"utf8",
		);
		// Drizzle's generated FK schema is public; isolate just that qualifier.
		await pool.query(migration.replaceAll('"public".', `"${schema}".`));
		await pool.query(
			"INSERT INTO organization VALUES ('one'),('two'); INSERT INTO library VALUES (1,'one'); INSERT INTO book(id,filename,library_id) VALUES (1,'Slayers [B07BBHFJTX].m4b',1); INSERT INTO audiobook_metadata(book_id,title) VALUES (1,'Slayers2');",
		);
		mock.module("@nanahoshi-v2/db", () => ({ db: drizzle(pool) }));
		const { AudiobookMetadataRepository } = await import(
			"../metadata.repository"
		);
		repo = new AudiobookMetadataRepository();
	});
	afterAll(async () => {
		await pool?.end();
		if (admin) {
			await admin.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE`);
			await admin.end();
		}
	});
	test("concurrent variants of a provider identity resolve to one series", async () => {
		const ids = await Promise.all([
			repo.upsertSeries("Mushoku Tensei", "one", identity),
			repo.upsertSeries("無職転生", "one", identity),
		]);
		expect(ids[0]).toBe(ids[1]);
		expect(
			(
				await pool.query(
					"SELECT count(*)::int AS count FROM audiobook_series_identity",
				)
			).rows[0].count,
		).toBe(1);
	});
	test("same names never collapse distinct identities, marketplaces, or servers", async () => {
		const first = await repo.upsertSeries("Mushoku Tensei", "one", identity);
		const second = await repo.upsertSeries("Mushoku Tensei", "one", {
			...identity,
			providerId: "B09133NYFN",
		});
		const region = await repo.upsertSeries("Mushoku Tensei", "one", {
			...identity,
			region: "us",
		});
		const server = await repo.upsertSeries("Mushoku Tensei", "two", identity);
		expect(new Set([first, second, region, server]).size).toBe(4);
	});
	test("adopts an exact legacy name without renaming unrelated groups", async () => {
		const old = await repo.upsertSeries("Slayers", "one");
		expect(
			await repo.upsertSeries("Slayers", "one", {
				...identity,
				providerId: "B07H7DVKM7",
			}),
		).toBe(old);
	});
	test("series refresh updates only its membership and ASIN", async () => {
		const before = await repo.getSeriesRefreshSnapshot(1);
		expect(before).toBeDefined();
		if (!before) throw new Error("Missing test record");
		const next = {
			series: {
				name: "Slayers",
				position: 2,
				sequence: "2",
				identity: { ...identity, providerId: "B07H7DVKM7" },
			},
			asin: "B07BBHFJTX",
		};
		expect(await repo.applySeriesRefresh(1, before, next)).toBe(true);
		const after = await repo.getSeriesRefreshSnapshot(1);
		expect(after?.metadata.title).toBe(before?.metadata.title);
		expect(after?.metadata.asin).toBe("B07BBHFJTX");
		expect(after?.series).toEqual([
			{ name: "Slayers", position: 2, sequence: "2" },
		]);
	});
	test("refuses stale snapshots and newly locked memberships", async () => {
		const before = await repo.getSeriesRefreshSnapshot(1);
		if (!before) throw new Error("Missing test record");
		await pool.query(
			"UPDATE audiobook_metadata SET locked_fields=ARRAY['series'] WHERE book_id=1",
		);
		const next = {
			series: {
				name: "Slayers",
				position: 3,
				identity: { ...identity, providerId: "B07H7DVKM7" },
			},
		};
		expect(await repo.applySeriesRefresh(1, before, next)).toBe(false);
		expect(
			await repo.applySeriesRefresh(
				1,
				{
					...before,
					metadata: { ...before.metadata, locked_fields: ["series"] },
				},
				next,
			),
		).toBe(false);
		expect((await repo.getSeriesRefreshSnapshot(1))?.series[0]?.position).toBe(
			2,
		);
		await pool.query(
			"UPDATE audiobook_metadata SET locked_fields='{}' WHERE book_id=1",
		);
	});
	test("a database failure rolls back both membership and provider identity", async () => {
		const before = await repo.getSeriesRefreshSnapshot(1);
		if (!before) throw new Error("Missing test record");
		await pool.query(
			`ALTER TABLE audiobook_metadata ADD CONSTRAINT reject_test_asin CHECK (asin <> 'B0FAIL0001')`,
		);
		await expect(
			repo.applySeriesRefresh(1, before, {
				series: {
					name: "Failed series",
					position: 99,
					identity: { ...identity, providerId: "B0FAIL0001" },
				},
				asin: "B0FAIL0001",
			}),
		).rejects.toThrow();
		expect(await repo.getSeriesRefreshSnapshot(1)).toEqual(before);
		expect(
			(
				await pool.query(
					"SELECT count(*)::int AS count FROM audiobook_series_identity WHERE provider_id='B0FAIL0001'",
				)
			).rows[0].count,
		).toBe(0);
	});
});
