"""Builds assets/fonts/SymbolsFilled.ttf and src/components/filled-symbols.ts:
every Android glyph in src/components/icon-names.ts at Material Symbols' FILL 1.

Usage: python3 scripts/filled-symbols.py <MaterialSymbolsOutlined[FILL,GRAD,opsz,wght].ttf>
(the variable font from github.com/google/material-design-icons/tree/master/variablefont)
"""

import json
import re
import sys
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

root = Path(__file__).resolve().parent.parent
names = sorted(
	set(re.findall(r'android: "([a-z0-9_]+)"', (root / "src/components/icon-names.ts").read_text()))
)
symbols = json.loads(
	(root / "node_modules/expo-symbols/build/android/symbols.json").resolve().read_text()
)
codepoints = {name: symbols[name] for name in names if name in symbols}

font = instancer.instantiateVariableFont(
	TTFont(sys.argv[1]), {"FILL": 1, "wght": 400, "GRAD": 0, "opsz": 24}
)
options = subset.Options()
options.layout_features = []
options.name_IDs = []
subsetter = subset.Subsetter(options)
subsetter.populate(unicodes=codepoints.values())
subsetter.subset(font)
font["name"].setName("SymbolsFilled", 1, 3, 1, 0x409)
font["name"].setName("SymbolsFilled", 4, 3, 1, 0x409)
font["name"].setName("SymbolsFilled", 6, 3, 1, 0x409)
font.save(root / "assets/fonts/SymbolsFilled.ttf")

entries = "\n".join(f"\t{name}: 0x{cp:x}," for name, cp in codepoints.items())
(root / "src/components/filled-symbols.ts").write_text(
	"// Generated by scripts/filled-symbols.py: the glyphs in SymbolsFilled.ttf.\n"
	f"export const FILLED_SYMBOLS: Record<string, number> = {{\n{entries}\n}};\n"
)
print(f"{len(codepoints)} glyphs; missing: {sorted(set(names) - set(codepoints))}")
