import type {
	CollectionRuleField,
	CollectionRuleOperator,
	CollectionSortField,
} from "@nanahoshi-v2/api/routers/collections/collection-rules";

type SupportedLocale = "en" | "es" | "ja";

const FIELD_LABELS: Record<
	SupportedLocale,
	Record<CollectionRuleField | CollectionSortField, string>
> = {
	en: {
		mediaType: "Media type",
		title: "Title",
		subtitle: "Subtitle",
		filename: "File name",
		author: "Author",
		narrator: "Narrator",
		publisher: "Publisher",
		series: "Series",
		seriesPosition: "Series position",
		genre: "Genre",
		tag: "Tag",
		language: "Language",
		contentForm: "Content form",
		format: "File format",
		fileSizeMb: "File size (MB)",
		addedAt: "Date added",
		lastModifiedAt: "Last modified",
		publishedDate: "Publication date",
		publishedYear: "Publication year",
		pageCount: "Page count",
		durationMinutes: "Duration (minutes)",
		communityRating: "Community rating",
		communityRatingCount: "Rating count",
		cover: "Cover",
		description: "Description",
		isbn: "ISBN",
		asin: "ASIN",
		explicit: "Explicit content",
		abridged: "Abridged",
		library: "Library",
		manualCollection: "Manual collection",
		enrichmentStatus: "Metadata status",
		metadataLocked: "Metadata locked",
		readListenPaired: "Read & Listen pair",
		liked: "Liked",
		shelfStatus: "Shelf",
		consumptionStatus: "Reading status",
		progressPercent: "Progress (%)",
		startedAt: "Started date",
		completedAt: "Completed date",
		lastActivityAt: "Last activity",
		primaryAuthor: "Primary author",
		random: "Random",
	},
	es: {
		mediaType: "Tipo de contenido",
		title: "Título",
		subtitle: "Subtítulo",
		filename: "Nombre del archivo",
		author: "Autor",
		narrator: "Narrador",
		publisher: "Editorial",
		series: "Serie",
		seriesPosition: "Posición en la serie",
		genre: "Género",
		tag: "Etiqueta",
		language: "Idioma",
		contentForm: "Forma del contenido",
		format: "Formato del archivo",
		fileSizeMb: "Tamaño del archivo (MB)",
		addedAt: "Fecha de incorporación",
		lastModifiedAt: "Última modificación",
		publishedDate: "Fecha de publicación",
		publishedYear: "Año de publicación",
		pageCount: "Número de páginas",
		durationMinutes: "Duración (minutos)",
		communityRating: "Valoración de la comunidad",
		communityRatingCount: "Número de valoraciones",
		cover: "Portada",
		description: "Descripción",
		isbn: "ISBN",
		asin: "ASIN",
		explicit: "Contenido explícito",
		abridged: "Versión abreviada",
		library: "Biblioteca",
		manualCollection: "Colección manual",
		enrichmentStatus: "Estado de metadatos",
		metadataLocked: "Metadatos bloqueados",
		readListenPaired: "Pareja Leer y escuchar",
		liked: "Me gusta",
		shelfStatus: "Estante",
		consumptionStatus: "Estado de lectura",
		progressPercent: "Progreso (%)",
		startedAt: "Fecha de inicio",
		completedAt: "Fecha de finalización",
		lastActivityAt: "Última actividad",
		primaryAuthor: "Autor principal",
		random: "Aleatorio",
	},
	ja: {
		mediaType: "メディアの種類",
		title: "タイトル",
		subtitle: "サブタイトル",
		filename: "ファイル名",
		author: "著者",
		narrator: "ナレーター",
		publisher: "出版社",
		series: "シリーズ",
		seriesPosition: "シリーズ内の位置",
		genre: "ジャンル",
		tag: "タグ",
		language: "言語",
		contentForm: "コンテンツ形式",
		format: "ファイル形式",
		fileSizeMb: "ファイルサイズ (MB)",
		addedAt: "追加日",
		lastModifiedAt: "更新日",
		publishedDate: "出版日",
		publishedYear: "出版年",
		pageCount: "ページ数",
		durationMinutes: "再生時間（分）",
		communityRating: "コミュニティ評価",
		communityRatingCount: "評価数",
		cover: "表紙",
		description: "説明",
		isbn: "ISBN",
		asin: "ASIN",
		explicit: "成人向けコンテンツ",
		abridged: "抄訳版",
		library: "ライブラリ",
		manualCollection: "手動コレクション",
		enrichmentStatus: "メタデータ状態",
		metadataLocked: "メタデータをロック",
		readListenPaired: "読む・聴くペア",
		liked: "お気に入り",
		shelfStatus: "本棚",
		consumptionStatus: "読書状態",
		progressPercent: "進捗 (%)",
		startedAt: "開始日",
		completedAt: "完了日",
		lastActivityAt: "最後のアクティビティ",
		primaryAuthor: "主著者",
		random: "ランダム",
	},
};

const OPERATOR_LABELS: Record<
	SupportedLocale,
	Record<CollectionRuleOperator, string>
> = {
	en: {
		contains: "contains",
		notContains: "does not contain",
		startsWith: "starts with",
		endsWith: "ends with",
		equals: "is",
		notEquals: "is not",
		isMissing: "is missing",
		isPresent: "is present",
		includesAny: "includes any of",
		includesAll: "includes all of",
		excludesAll: "includes none of",
		gt: "is greater than",
		gte: "is at least",
		lt: "is less than",
		lte: "is at most",
		between: "is between",
		before: "is before",
		after: "is after",
		withinLast: "is within the last",
		isTrue: "is yes",
		isFalse: "is no",
		isUnknown: "is unknown",
	},
	es: {
		contains: "contiene",
		notContains: "no contiene",
		startsWith: "empieza por",
		endsWith: "termina en",
		equals: "es",
		notEquals: "no es",
		isMissing: "no tiene valor",
		isPresent: "tiene valor",
		includesAny: "incluye cualquiera de",
		includesAll: "incluye todos",
		excludesAll: "no incluye ninguno de",
		gt: "es mayor que",
		gte: "es como mínimo",
		lt: "es menor que",
		lte: "es como máximo",
		between: "está entre",
		before: "es anterior a",
		after: "es posterior a",
		withinLast: "está dentro de los últimos",
		isTrue: "sí",
		isFalse: "no",
		isUnknown: "se desconoce",
	},
	ja: {
		contains: "次を含む",
		notContains: "次を含まない",
		startsWith: "次で始まる",
		endsWith: "次で終わる",
		equals: "次と同じ",
		notEquals: "次と異なる",
		isMissing: "値がない",
		isPresent: "値がある",
		includesAny: "いずれかを含む",
		includesAll: "すべてを含む",
		excludesAll: "いずれも含まない",
		gt: "次より大きい",
		gte: "次以上",
		lt: "次より小さい",
		lte: "次以下",
		between: "範囲内",
		before: "次より前",
		after: "次より後",
		withinLast: "直近の期間内",
		isTrue: "はい",
		isFalse: "いいえ",
		isUnknown: "不明",
	},
};

const VALUE_LABELS: Record<SupportedLocale, Record<string, string>> = {
	en: {
		all: "All",
		any: "Any",
		asc: "Ascending",
		desc: "Descending",
		day: "days",
		week: "weeks",
		month: "months",
		ebook: "Ebook",
		audiobook: "Audiobook",
		readListen: "Read & Listen",
		text: "Text",
		images: "Images / comic",
		pending: "Pending",
		enriched: "Enriched",
		partial: "Partial",
		no_match: "No match",
		review: "Needs review",
		notRun: "Not processed",
		want: "Want to start",
		backlog: "Backlog",
		inProgress: "In progress",
		completed: "Completed",
		none: "No shelf",
		unstarted: "Not started",
	},
	es: {
		all: "Todas",
		any: "Cualquiera",
		asc: "Ascendente",
		desc: "Descendente",
		day: "días",
		week: "semanas",
		month: "meses",
		ebook: "Ebook",
		audiobook: "Audiolibro",
		readListen: "Leer y escuchar",
		text: "Texto",
		images: "Imágenes / cómic",
		pending: "Pendiente",
		enriched: "Completos",
		partial: "Parciales",
		no_match: "Sin coincidencia",
		review: "Necesitan revisión",
		notRun: "Sin procesar",
		want: "Quiero empezar",
		backlog: "Pendiente",
		inProgress: "En curso",
		completed: "Completado",
		none: "Sin estante",
		unstarted: "Sin empezar",
	},
	ja: {
		all: "すべて",
		any: "いずれか",
		asc: "昇順",
		desc: "降順",
		day: "日",
		week: "週間",
		month: "か月",
		ebook: "電子書籍",
		audiobook: "オーディオブック",
		readListen: "読む・聴く",
		text: "テキスト",
		images: "画像・コミック",
		pending: "保留中",
		enriched: "取得済み",
		partial: "一部のみ",
		no_match: "一致なし",
		review: "確認が必要",
		notRun: "未処理",
		want: "始めたい",
		backlog: "あとで",
		inProgress: "進行中",
		completed: "完了",
		none: "本棚なし",
		unstarted: "未開始",
	},
};

const TEMPLATE_LABELS: Record<SupportedLocale, Record<string, string>> = {
	en: {
		recentlyAdded: "Recently added",
		continueReading: "Continue reading",
		shortEbooks: "Short ebooks",
		shortAudiobooks: "Short audiobooks",
		missingCover: "Missing cover",
		metadataNeedsAttention: "Metadata needs attention",
		onlyEpub: "Only EPUB",
		onlyPdf: "Only PDF",
		withoutGenres: "Without genres",
		inSeries: "In a series",
		recentPicks: "Recent picks",
		shortBooksAnyFormat: "Short books in any format",
		favoritesToFinish: "Favorites to finish",
	},
	es: {
		recentlyAdded: "Añadidos recientemente",
		continueReading: "Continuar leyendo",
		shortEbooks: "Ebooks cortos",
		shortAudiobooks: "Audiolibros cortos",
		missingCover: "Sin portada",
		metadataNeedsAttention: "Metadatos por revisar",
		onlyEpub: "Solo EPUB",
		onlyPdf: "Solo PDF",
		withoutGenres: "Sin géneros",
		inSeries: "Dentro de una serie",
		recentPicks: "Selecciones recientes",
		shortBooksAnyFormat: "Libros cortos en cualquier formato",
		favoritesToFinish: "Favoritos por terminar",
	},
	ja: {
		recentlyAdded: "最近追加",
		continueReading: "読書を続ける",
		shortEbooks: "短い電子書籍",
		shortAudiobooks: "短いオーディオブック",
		missingCover: "表紙なし",
		metadataNeedsAttention: "メタデータ要確認",
		onlyEpub: "EPUBのみ",
		onlyPdf: "PDFのみ",
		withoutGenres: "ジャンルなし",
		inSeries: "シリーズ作品",
		recentPicks: "最近のおすすめ",
		shortBooksAnyFormat: "形式を問わない短い本",
		favoritesToFinish: "読み終えていないお気に入り",
	},
};

export const COLLECTION_FIELD_GROUPS = [
	{
		id: "identity",
		fields: ["mediaType", "title", "subtitle", "filename"] as const,
	},
	{
		id: "people",
		fields: [
			"author",
			"narrator",
			"publisher",
			"series",
			"seriesPosition",
		] as const,
	},
	{
		id: "catalog",
		fields: [
			"genre",
			"tag",
			"language",
			"contentForm",
			"publishedDate",
			"publishedYear",
			"communityRating",
			"communityRatingCount",
			"description",
			"isbn",
			"asin",
			"pageCount",
			"durationMinutes",
		] as const,
	},
	{
		id: "file",
		fields: [
			"format",
			"fileSizeMb",
			"addedAt",
			"lastModifiedAt",
			"cover",
		] as const,
	},
	{
		id: "library",
		fields: [
			"library",
			"manualCollection",
			"enrichmentStatus",
			"metadataLocked",
			"readListenPaired",
			"explicit",
			"abridged",
		] as const,
	},
	{
		id: "personal",
		fields: [
			"liked",
			"shelfStatus",
			"consumptionStatus",
			"progressPercent",
			"startedAt",
			"completedAt",
			"lastActivityAt",
		] as const,
	},
] satisfies ReadonlyArray<{
	id: string;
	fields: readonly CollectionRuleField[];
}>;

function localeKey(locale: string): SupportedLocale {
	if (locale.startsWith("es")) return "es";
	if (locale.startsWith("ja")) return "ja";
	return "en";
}

export function fieldLabel(
	field: CollectionRuleField | CollectionSortField,
	locale: string,
) {
	return FIELD_LABELS[localeKey(locale)][field];
}

export function operatorLabel(
	operator: CollectionRuleOperator,
	locale: string,
) {
	return OPERATOR_LABELS[localeKey(locale)][operator];
}

export function valueLabel(value: string, locale: string) {
	return VALUE_LABELS[localeKey(locale)][value] ?? value;
}

export function templateLabel(value: string, locale: string) {
	return TEMPLATE_LABELS[localeKey(locale)][value] ?? value;
}
