name: "Setup Bun"
description: "Sets up Bun with caching and installation"

runs:
  using: composite
  steps:
    - name: Extract versions from .tool-versions
      id: versions
      shell: bash
      run: |
        BUN_VERSION=$(grep 'bun' .tool-versions | awk '{print $2}')
        NODE_VERSION=$(grep 'nodejs' .tool-versions | awk '{print $2}')
        echo "bun=$BUN_VERSION" >> $GITHUB_OUTPUT
        echo "node=$NODE_VERSION" >> $GITHUB_OUTPUT

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ steps.versions.outputs.bun }}

    - name: Cache bun dependencies
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      with:
        path: |
          ~/.bun/install/cache
          node_modules
        key: ${{ runner.os }}-node-${{ steps.versions.outputs.node }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ steps.versions.outputs.node }}-bun-

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile